// frontend-angular/src/app/features/analytics/analytics-zone.component.ts
import { Component, EventEmitter, inject, Input, OnInit, Output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';

import { WidgetsApiService, SavedReport, ReportsApiService } from '../../core/services';

interface KpiData {
  id: string;
  title: string;
  value: string | number;
  footer?: string;
}

const FALLBACK_KPIS: KpiData[] = [
  { id: 'total-evaluations', title: 'Total Évaluations', value: '—', footer: 'Chargement...' },
  { id: 'note-moyenne', title: 'Note Moyenne', value: '—', footer: 'Chargement...' },
  { id: 'commentaires', title: 'Commentaires', value: '—', footer: 'Chargement...' },
  { id: 'sentiment', title: 'Sentiment', value: '—', footer: 'Chargement...' },
];

@Component({
  selector: 'app-analytics-zone',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  template: `
    <div
      class="flex flex-col bg-background transition-all duration-300 ease-in-out"
      [class.w-14]="collapsed()"
      [style.width]="collapsed() ? null : width() + '%'"
    >
      @if (collapsed()) {
        <div class="flex-1 flex flex-col items-center pt-3">
          <button
            (click)="toggleCollapse()"
            class="w-10 h-10 bg-secondary hover:bg-accent rounded-lg flex items-center justify-center transition-colors"
            [title]="'analytics.open' | translate"
          >
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </button>
        </div>
      } @else {
        <!-- Header -->
        <div class="h-12 px-3 border-b border-border/50 bg-secondary/30 flex items-center justify-between flex-shrink-0">
          <h3 class="text-xs font-semibold text-amber-400 uppercase tracking-wider flex items-center gap-2">
            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
            {{ 'analytics.title' | translate }}
          </h3>
          <button
            (click)="toggleCollapse()"
            class="h-7 w-7 p-0 hover:bg-amber-500/20 rounded flex items-center justify-center"
            [title]="'common.collapse' | translate"
          >
            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
          </button>
        </div>

        <!-- Scrollable content -->
        <div class="flex-1 overflow-y-auto p-2 space-y-3">
          <!-- Saved Reports -->
          @if (savedReports().length > 0) {
            <div class="pb-2 border-b border-amber-500/10">
              <h4 class="text-[9px] text-amber-400/70 uppercase tracking-wider mb-1.5 flex items-center gap-1">
                <svg class="w-2.5 h-2.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
                </svg>
                {{ 'analytics.reports' | translate }}
              </h4>
              <div class="space-y-1">
                @for (report of savedReports().slice(0, 5); track report.id) {
                  <div
                    class="p-1.5 rounded border border-border/30 hover:bg-secondary/50 hover:border-primary/30 transition-all group cursor-pointer"
                    (click)="onReportClick.emit(report)"
                  >
                    <div class="flex items-center justify-between">
                      <p class="text-[10px] truncate text-foreground/80 flex-1">
                        {{ report.title }}
                      </p>
                      <div class="flex items-center gap-1 opacity-0 group-hover:opacity-100">
                        <button
                          (click)="deleteReport(report, $event)"
                          class="text-[8px] text-destructive"
                        >
                          ✕
                        </button>
                      </div>
                    </div>
                  </div>
                }
              </div>
            </div>
          }

          <!-- KPIs -->
          <div class="flex flex-col gap-2">
            @for (kpi of kpis(); track kpi.id) {
              <div class="bg-secondary/30 border border-border/50 rounded-xl p-4">
                <p class="text-xs text-muted-foreground mb-2">{{ kpi.title }}</p>
                <p class="text-2xl font-bold text-foreground tabular-nums mb-3">
                  {{ formatValue(kpi.value) }}
                </p>
                @if (kpi.footer) {
                  <p class="text-xs text-muted-foreground">{{ kpi.footer }}</p>
                }
              </div>
            }
          </div>
        </div>
      }
    </div>
  `,
})
export class AnalyticsZoneComponent implements OnInit {
  private readonly widgetsApi = inject(WidgetsApiService);
  private readonly reportsApi = inject(ReportsApiService);

  @Input() set collapsedInput(value: boolean) {
    this.collapsed.set(value);
  }
  @Input() set widthInput(value: number) {
    this.width.set(value);
  }

  @Output() collapseChange = new EventEmitter<boolean>();
  @Output() onReportClick = new EventEmitter<SavedReport>();
  @Output() onReportDelete = new EventEmitter<number>();

  protected readonly collapsed = signal(false);
  protected readonly width = signal(20);
  protected readonly kpis = signal<KpiData[]>(FALLBACK_KPIS);
  protected readonly savedReports = signal<SavedReport[]>([]);

  ngOnInit(): void {
    this.loadKpis();
    this.loadReports();
  }

  private loadKpis(): void {
    this.widgetsApi.getKpis().subscribe({
      next: (data) => {
        if (data.length > 0) {
          this.kpis.set(data.map(k => ({
            id: k.id,
            title: k.title,
            value: k.value,
            footer: k.footer,
          })));
        }
      },
    });
  }

  private loadReports(): void {
    this.reportsApi.getReports().subscribe({
      next: (reports: SavedReport[]) => {
        this.savedReports.set(reports);
      },
    });
  }

  toggleCollapse(): void {
    const newValue = !this.collapsed();
    this.collapsed.set(newValue);
    this.collapseChange.emit(newValue);
  }

  deleteReport(report: SavedReport, event: Event): void {
    event.stopPropagation();
    this.onReportDelete.emit(report.id);
  }

  formatValue(value: string | number): string {
    if (typeof value === 'number') {
      return value.toLocaleString('fr-FR');
    }
    return value;
  }
}

// g7-analytics/src/components/AnalyticsZone.tsx
"use client";

import { Button } from "@/components/ui/button";
import { SemanticStats, SavedReport } from "@/types";

interface AnalyticsZoneProps {
  collapsed: boolean;
  onCollapse: (collapsed: boolean) => void;
  width: number;
  isResizing: boolean;
  semanticStats: SemanticStats | null;
  savedReports: SavedReport[];
  onReportClick: (report: SavedReport) => void;
  onReportDelete: (id: number) => void;
}

export function AnalyticsZone({
  collapsed,
  onCollapse,
  width,
  isResizing,
  semanticStats,
  savedReports,
  onReportClick,
  onReportDelete,
}: AnalyticsZoneProps) {
  return (
    <div
      className={`flex flex-col bg-[hsl(260_10%_10%)] ${collapsed ? "w-14" : ""} ${isResizing ? "" : "transition-all duration-300 ease-in-out"}`}
      style={collapsed ? undefined : { width: `${width}%` }}
    >
      {collapsed ? (
        <div className="flex-1 flex flex-col items-center pt-3">
          <button
            onClick={() => onCollapse(false)}
            className="w-10 h-10 bg-secondary hover:bg-accent rounded-lg flex items-center justify-center transition-colors"
            title="Ouvrir Analyse IA"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M3 3v18h18" />
              <path d="M18 9l-5 5-4-4-3 3" />
            </svg>
          </button>
        </div>
      ) : (
        <>
          {/* Header Zone 3 */}
          <div className="h-12 px-3 border-b border-amber-500/20 bg-gradient-to-r from-amber-500/10 to-transparent flex items-center justify-between">
            <h3 className="text-xs font-semibold text-amber-400 uppercase tracking-wider flex items-center gap-2">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M3 3v18h18" />
                <path d="M18 9l-5 5-4-4-3 3" />
              </svg>
              Analyse IA
            </h3>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 w-7 p-0 hover:bg-amber-500/20"
              onClick={() => onCollapse(true)}
              title="Réduire le panneau"
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M13 19l7-7-7-7M6 19l7-7-7-7" />
              </svg>
            </Button>
          </div>

          {/* Contenu scrollable */}
          <div className="flex-1 overflow-y-auto">
            {/* KPIs Sémantiques */}
            {semanticStats && (
              <div className="p-3 space-y-3">
                {/* KPI Cards */}
                <div className="grid grid-cols-2 gap-2">
                  <div className="bg-gradient-to-br from-emerald-500/10 to-transparent border border-emerald-500/20 rounded-lg p-2.5 text-center relative group">
                    <div className="absolute top-1 right-1 w-4 h-4 rounded-full bg-emerald-500/20 flex items-center justify-center cursor-help hover:bg-emerald-500/40 transition-colors peer">
                      <span className="text-[9px] font-medium text-emerald-400">i</span>
                    </div>
                    <div className="absolute top-6 right-0 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-[100]">
                      <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-2.5 text-[10px] text-zinc-300 w-44 shadow-2xl">
                        Score moyen de sentiment des commentaires analysés. Échelle de -1 (très négatif) à +1 (très positif).
                      </div>
                    </div>
                    <p className="text-[10px] text-emerald-400/70 uppercase tracking-wider">Sentiment</p>
                    <p className={`text-lg font-bold ${semanticStats.global.sentiment_moyen >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      {semanticStats.global.sentiment_moyen >= 0 ? '+' : ''}{semanticStats.global.sentiment_moyen.toFixed(2)}
                    </p>
                  </div>
                  <div className="bg-gradient-to-br from-blue-500/10 to-transparent border border-blue-500/20 rounded-lg p-2.5 text-center relative group">
                    <div className="absolute top-1 right-1 w-4 h-4 rounded-full bg-blue-500/20 flex items-center justify-center cursor-help hover:bg-blue-500/40 transition-colors">
                      <span className="text-[9px] font-medium text-blue-400">i</span>
                    </div>
                    <div className="absolute top-6 right-0 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-[100]">
                      <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-2.5 text-[10px] text-zinc-300 w-44 shadow-2xl">
                        Pourcentage de commentaires analysés par l'IA ({semanticStats.global.commentaires_enrichis.toLocaleString('fr-FR')} / {semanticStats.global.total_commentaires.toLocaleString('fr-FR')}).
                      </div>
                    </div>
                    <p className="text-[10px] text-blue-400/70 uppercase tracking-wider">Enrichis</p>
                    <p className="text-lg font-bold text-blue-400">
                      {semanticStats.global.taux_enrichissement}%
                    </p>
                  </div>
                </div>

                {/* Sentiment Distribution - Mini Bar Chart */}
                <div className="bg-secondary/30 rounded-lg p-2.5 relative group">
                  <div className="absolute top-2 right-2 w-4 h-4 rounded-full bg-muted hover:bg-muted/80 flex items-center justify-center cursor-help transition-colors">
                    <span className="text-[9px] font-medium text-muted-foreground">i</span>
                  </div>
                  <div className="absolute top-7 right-0 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-[100]">
                    <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-2.5 text-[10px] text-zinc-300 w-48 shadow-2xl">
                      Répartition des commentaires par niveau de sentiment. Le % indique la proportion sur le total analysé.
                    </div>
                  </div>
                  <p className="text-[10px] text-muted-foreground uppercase tracking-wider mb-2">Distribution Sentiments</p>
                  <div className="space-y-1.5">
                    {semanticStats.sentiment_distribution.map((item, idx) => {
                      const total = semanticStats.sentiment_distribution.reduce((a, b) => a + b.count, 0);
                      const pct = (item.count / total * 100).toFixed(0);
                      const colors: Record<string, string> = {
                        'Très positif': 'bg-emerald-500',
                        'Positif': 'bg-emerald-400',
                        'Neutre': 'bg-gray-400',
                        'Négatif': 'bg-orange-400',
                        'Très négatif': 'bg-red-500'
                      };
                      return (
                        <div key={idx} className="flex items-center gap-2">
                          <span className="text-[10px] text-muted-foreground min-w-[4.5rem] shrink-0">{item.label}</span>
                          <div className="flex-1 h-2 bg-secondary rounded-full overflow-hidden min-w-[2rem]">
                            <div
                              className={`h-full ${colors[item.label] || 'bg-primary'} transition-all`}
                              style={{ width: `${pct}%` }}
                            />
                          </div>
                          <span className="text-[10px] text-muted-foreground whitespace-nowrap">{pct}%</span>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* ALERTES - Catégories avec sentiment négatif */}
                {semanticStats.alerts && semanticStats.alerts.length > 0 && (
                  <div className="bg-gradient-to-br from-red-500/10 to-transparent border border-red-500/20 rounded-lg p-2.5 relative group">
                    <div className="absolute top-2 right-2 w-4 h-4 rounded-full bg-red-500/20 hover:bg-red-500/40 flex items-center justify-center cursor-help transition-colors">
                      <span className="text-[9px] font-medium text-red-400">i</span>
                    </div>
                    <div className="absolute top-7 right-0 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-[100]">
                      <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-2.5 text-[10px] text-zinc-300 w-52 shadow-2xl">
                        <p className="font-medium text-red-400 mb-1">Points d'attention</p>
                        <p>Catégories avec le plus de commentaires négatifs. Ce sont les axes d'amélioration prioritaires.</p>
                      </div>
                    </div>
                    <p className="text-[10px] text-red-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                      <span>⚠</span> Alertes
                    </p>
                    <div className="space-y-1.5">
                      {semanticStats.alerts.map((item, idx) => {
                        const displayName = item.category.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, l => l.toUpperCase());
                        return (
                          <div key={idx} className="flex items-center gap-2 p-1.5 bg-red-500/5 rounded border border-red-500/10">
                            <span className="text-[10px] text-foreground/80 truncate min-w-0 flex-1" title={displayName}>
                              {displayName}
                            </span>
                            <span className="text-[9px] text-muted-foreground whitespace-nowrap">{item.count.toLocaleString('fr-FR')}</span>
                            <span className="text-[10px] font-medium text-red-400 whitespace-nowrap">
                              {item.sentiment.toFixed(2)}
                            </span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

                {/* POINTS FORTS - Catégories avec sentiment positif */}
                {semanticStats.strengths && semanticStats.strengths.length > 0 && (
                  <div className="bg-gradient-to-br from-emerald-500/10 to-transparent border border-emerald-500/20 rounded-lg p-2.5 relative group">
                    <div className="absolute top-2 right-2 w-4 h-4 rounded-full bg-emerald-500/20 hover:bg-emerald-500/40 flex items-center justify-center cursor-help transition-colors">
                      <span className="text-[9px] font-medium text-emerald-400">i</span>
                    </div>
                    <div className="absolute top-7 right-0 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity duration-200 z-[100]">
                      <div className="bg-zinc-900 border border-zinc-700 rounded-lg p-2.5 text-[10px] text-zinc-300 w-52 shadow-2xl">
                        <p className="font-medium text-emerald-400 mb-1">Points forts</p>
                        <p>Catégories avec le plus de commentaires positifs. Ce sont vos atouts à capitaliser.</p>
                      </div>
                    </div>
                    <p className="text-[10px] text-emerald-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                      <span>✓</span> Points Forts
                    </p>
                    <div className="space-y-1.5">
                      {semanticStats.strengths.map((item, idx) => {
                        const displayName = item.category.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, l => l.toUpperCase());
                        return (
                          <div key={idx} className="flex items-center gap-2 p-1.5 bg-emerald-500/5 rounded border border-emerald-500/10">
                            <span className="text-[10px] text-foreground/80 truncate min-w-0 flex-1" title={displayName}>
                              {displayName}
                            </span>
                            <span className="text-[9px] text-muted-foreground whitespace-nowrap">{item.count.toLocaleString('fr-FR')}</span>
                            <span className="text-[10px] font-medium text-emerald-400 whitespace-nowrap">
                              +{item.sentiment.toFixed(2)}
                            </span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}

              </div>
            )}

            {/* Separator */}
            <div className="border-t border-amber-500/20 mx-3" />

            {/* Rapports sauvegardés */}
            <div className="p-3">
              <h4 className="text-[10px] text-amber-400/70 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z" />
                </svg>
                Rapports
              </h4>
              <div className="space-y-1.5">
                {savedReports.length === 0 ? (
                  <p className="text-[10px] text-muted-foreground text-center py-2">
                    Aucun rapport
                  </p>
                ) : (
                  savedReports.slice(0, 5).map((report) => (
                    <div
                      key={report.id}
                      className="p-2 rounded-lg border border-border/50 hover:bg-secondary/50 hover:border-primary/30 transition-all group cursor-pointer"
                      onClick={() => onReportClick(report)}
                    >
                      <p className="text-[11px] font-medium truncate text-foreground">
                        {report.is_pinned ? <span className="text-primary mr-1">●</span> : null}
                        {report.title}
                      </p>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          onReportDelete(report.id);
                        }}
                        className="text-[9px] text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
                      >
                        Supprimer
                      </button>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
